# Generated by Django 4.2.6 on 2023-12-16 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='index/img')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='index/img')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=300)),
                ('status', models.CharField(choices=[('YR', 'Yaroqli'), ('YS', 'Yaroqsiz')], default='YR', max_length=2)),
            ],
        ),
    ]
