# Generated by Django 4.2.6 on 2023-12-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='index/img')),
                ('number', models.IntegerField()),
                ('time', models.FloatField()),
                ('tname', models.CharField(max_length=300)),
                ('snumber', models.TextField()),
            ],
        ),
    ]
