# Generated by Django 4.2.6 on 2023-12-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_aexp_cour_exp_instruct'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='img',
            field=models.ImageField(default=1, upload_to='index/img'),
            preserve_default=False,
        ),
    ]
