# Generated by Django 4.2.6 on 2023-12-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_exp_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='aexp',
            name='img',
            field=models.ImageField(default=1, upload_to='about/img'),
            preserve_default=False,
        ),
    ]
