# Generated by Django 5.0 on 2023-12-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cost', models.IntegerField()),
                ('slug', models.SlugField(max_length=300)),
                ('tutor', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('numPupils', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
