# Generated by Django 5.0 on 2023-12-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='img',
            field=models.ImageField(default=1, upload_to='index/img'),
            preserve_default=False,
        ),
    ]
